controllers/MachineController.php
<?php

namespace app\controllers;

use app\models\data\Inspection;
use app\models\data\PlannedWork;
use app\models\data\RepairTask;
use app\models\data\Work;
use app\models\search\ExaminationSearch;
use app\models\search\InspectionSearch;
use app\models\search\PlannedWorkSearch;
use app\models\search\RepairTaskSearch;
use app\models\search\WorkSearch;
use Yii;
use app\models\data\Machine;
use app\models\search\MachineSearch;
use yii\data\ActiveDataProvider;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\models\data\User;
use app\models\notification\WorkNotification;
use yii\filters\AccessControl;

/**
 * MachineController implements the CRUD actions for Machine model.
 */
class MachineController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    /**
     * Lists all Machine models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new MachineSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Machine model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        $model = $this->findModel($id);

//        $user = User::findOne(Yii::$app->user->id);
//        WorkNotification::create(WorkNotification::DAILY_FOR_ENGINEERS, ['user' => $user])->send();

        $examinationSearchModel = new ExaminationSearch(['machine_id' => $model->id]);
        $examinationDataProvider = $examinationSearchModel->search(Yii::$app->request->queryParams);

        $plannedWorkSearchModel = new PlannedWorkSearch(['machine_id' => $model->id]);
        $plannedWorkDataProvider = $plannedWorkSearchModel->search(Yii::$app->request->queryParams);

        $workSearchModel = new WorkSearch(['machine_id' => $model->id]);
        $workDataProvider = $workSearchModel->search(Yii::$app->request->queryParams);

        $inspectionsSearchModel = new InspectionSearch(['machine_id' => $model->id]);
        $inspectionsDataProvider = $inspectionsSearchModel->search(Yii::$app->request->queryParams);

        $repairTasksSearchModel = new RepairTaskSearch(['machine_id' => $model->id]);
        $repairTasksDataProvider = $repairTasksSearchModel->search(Yii::$app->request->queryParams);

        return $this->render('view', [
            'model' => $model,

            'examinationSearchModel' => $examinationSearchModel,
            'plannedWorkSearchModel' => $plannedWorkSearchModel,
            'workSearchModel' => $workSearchModel,
            'inspectionsSearchModel' => $inspectionsSearchModel,
            'repairTasksSearchModel' => $repairTasksSearchModel,

            'examinationDataProvider' => $examinationDataProvider,
            'inspectionsDataProvider' => $inspectionsDataProvider,
            'workDataProvider' => $workDataProvider,
            'repairTasksDataProvider' => $repairTasksDataProvider,
            'plannedWorkDataProvider' => $plannedWorkDataProvider
        ]);
    }

    public function actionTasks($id)
    {
        $machineModel = $this->findModel($id);
        $tasks = $machineModel->getTasks(Yii::$app->user->id);


        return $this->render('tasks', [
            'machineModel' => $machineModel,
            'tasks' => $tasks
        ]);
    }

    public function actionQrCode($id)
    {
        $model = $this->findModel($id);

        return $this->render('qr-code', [
            'model' => $model,
        ]);
    }

    /**
     * Creates a new Machine model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Machine();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['update', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Machine model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Machine model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Machine model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Machine the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Machine::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

controllers/PlannedWorkController.php
<?php

namespace app\controllers;

use app\models\search\PlannedWorkTaskSearch;
use Yii;
use app\models\data\PlannedWork;
use app\models\search\PlannedWorkSearch;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * PlannedWorkController implements the CRUD actions for PlannedWork model.
 */
class PlannedWorkController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    /**
     * Lists all PlannedWork models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new PlannedWorkSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single PlannedWork model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        $model = $this->findModel($id);

        $plannedWorkTaskSearchModel = new PlannedWorkTaskSearch(['planned_work_id' => $model->id]);
        $plannedWorkTaskDataProvider = $plannedWorkTaskSearchModel->search(Yii::$app->request->queryParams);

        return $this->render('view', [
            'model' => $model,
            'plannedWorkTaskSearchModel' => $plannedWorkTaskSearchModel,
            'plannedWorkTaskDataProvider' => $plannedWorkTaskDataProvider
        ]);
    }

    /**
     * Creates a new PlannedWork model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate($machine_id)
    {
        $model = new PlannedWork([
            'machine_id' => $machine_id
        ]);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing PlannedWork model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing PlannedWork model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $model = $this->findModel($id);
        $model->delete();

        return $this->redirect($model->machine->getUrl());
    }

    /**
     * Finds the PlannedWork model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return PlannedWork the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = PlannedWork::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

controllers/PlannedWorkTaskController.php
<?php

namespace app\controllers;

use Yii;
use app\models\data\PlannedWorkTask;
use app\models\search\PlannedWorkTaskSearch;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * PlannedWorkTaskController implements the CRUD actions for PlannedWorkTask model.
 */
class PlannedWorkTaskController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    /**
     * Lists all PlannedWorkTask models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new PlannedWorkTaskSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single PlannedWorkTask model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new PlannedWorkTask model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate($planned_work_id)
    {
        $model = new PlannedWorkTask([
            'planned_work_id' => $planned_work_id
        ]);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['/planned-work/view', 'id' => $model->planned_work_id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing PlannedWorkTask model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['/planned-work/view', 'id' => $model->planned_work_id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing PlannedWorkTask model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(Yii::$app->request->referrer);
    }

    /**
     * Finds the PlannedWorkTask model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return PlannedWorkTask the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = PlannedWorkTask::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/planned-work/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use app\models\data\Machine;

/* @var $this yii\web\View */
/* @var $model app\models\data\PlannedWork */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="box box-default">
    <div class="box-body">
        <div class="planned-work-form">

            <?php $form = ActiveForm::begin(); ?>

            <div class="row">
                <div class="col-md-6">
                    <?php if ($model->machine->work_type == Machine::WORK_TYPE_DETAILS_COUNT): ?>
                        <?= $form->field($model, 'product_frequency')->textInput() ?>
                    <?php elseif ($model->machine->work_type == Machine::WORK_TYPE_PERIODS): ?>
                        <?= $form->field($model, 'day_frequency')->textInput() ?>
                    <?php endif; ?>

                    <?= $form->field($model, 'notes')->textarea(['rows' => 6, 'maxlength' => true]) ?>
                </div>
            </div>

            <div class="form-group">
                <?= Html::submitButton('Сохранить', ['class' => 'btn btn-success']) ?>
            </div>

            <?php ActiveForm::end(); ?>

        </div>
    </div>
</div>

views/planned-work/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\search\PlannedWorkSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="planned-work-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
        'options' => [
            'data-pjax' => 1
        ],
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'machine_id') ?>

    <?= $form->field($model, 'product_frequency') ?>

    <?= $form->field($model, 'day_frequency') ?>

    <?= $form->field($model, 'notes') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <?php // echo $form->field($model, 'created_by') ?>

    <?php // echo $form->field($model, 'updated_by') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/planned-work/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\data\PlannedWork */

$this->title = 'Добавить плановое ТО';
$this->params['breadcrumbs'][] = [
    'label' => $model->machine->name,
    'url' => ['/machine/view', 'id' => $model->machine_id]
];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="planned-work-create">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/planned-work/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;

/* @var $this yii\web\View */
/* @var $searchModel app\models\search\PlannedWorkSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Planned Works';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="box box-default">
    <div class="box-body">
        <div class="planned-work-index">

            <h1><?= Html::encode($this->title) ?></h1>
            <?php Pjax::begin(); ?>
            <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

            <p>
                <?= Html::a('Create Planned Work', ['create'], ['class' => 'btn btn-success']) ?>
            </p>

            <?= GridView::widget([
                'dataProvider' => $dataProvider,
                'filterModel' => $searchModel,
                'options' => [
                    'class' => 'table-responsive',
                ],
                'columns' => [
                    ['class' => 'yii\grid\SerialColumn'],

                    'id',
                    'machine_id',
                    'product_frequency',
                    'day_frequency',
                    'notes',
                    //'created_at',
                    //'updated_at',
                    //'created_by',
                    //'updated_by',

                    ['class' => 'yii\grid\ActionColumn'],
                ],
            ]); ?>
            <?php Pjax::end(); ?>
        </div>
    </div>
</div>

views/planned-work/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\data\PlannedWork */

$this->title = $model->getName();
$this->params['breadcrumbs'][] = [
    'label' => $model->machine->name,
    'url' => ['/machine/view', 'id' => $model->machine_id]
];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="planned-work-update">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/planned-work/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\grid\GridView;
use app\models\data\PlannedWorkTask;
use app\models\data\User;

/* @var $this yii\web\View */
/* @var $model app\models\data\PlannedWork */
/* @var $plannedWorkTaskSearchModel \app\models\search\PlannedWorkSearch */
/* @var $plannedWorkTaskDataProvider \yii\data\ActiveDataProvider */

$this->title = $model->getName();
$this->params['breadcrumbs'][] = [
    'label' => $model->machine->name,
    'url' => ['/machine/view', 'id' => $model->machine_id]
];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="planned-work-view">

    <p>
        <?php if (Yii::$app->user->can(User::ROLE_ADMIN)): ?>
            <?= Html::a('Редактировать', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
            <?= Html::a('Удалить', ['delete', 'id' => $model->id], [
                'class' => 'btn btn-danger',
                'data' => [
                    'confirm' => 'Вы уверены?',
                    'method' => 'post',
                ],
            ]) ?>
        <?php endif; ?>
    </p>

    <div class="box box-default">
        <div class="box-body">
            <div class="table-responsive">
                <?= DetailView::widget([
                    'model' => $model,
                    'attributes' => [
                        'id',
                        'frequencyStr',
                        'notes',
                    ],
                ]) ?>
            </div>
        </div>
    </div>

    <hr>
    <h3>Задачи</h3>
    <p>
        <?php if (Yii::$app->user->can(User::ROLE_ADMIN)): ?>
            <?= Html::a('Добавить задачу', ['/planned-work-task/create', 'planned_work_id' => $model->id],
                ['class' => 'btn btn-success']) ?>
        <?php endif; ?>
    </p>

    <?php
    $plannedWorkTaskGridViewButtonsTemplate = '';
    if (Yii::$app->user->can(User::ROLE_ADMIN)) {
        $plannedWorkTaskGridViewButtonsTemplate .= ' {update} {delete}';
    }
    ?>

    <div class="box box-default">
        <div class="box-body">
            <?= GridView::widget([
                'dataProvider' => $plannedWorkTaskDataProvider,
//            'filterModel' => $plannedWorkTaskSearchModel,
                'options' => [
                    'class' => 'table-responsive',
                ],
                'columns' => [
                    'name',
                    [
                        'class' => 'yii\grid\ActionColumn',
                        'template' => $plannedWorkTaskGridViewButtonsTemplate,
                        'buttons' => [
                            'update' => function ($url, PlannedWorkTask $model) {
                                return Html::a('Редактировать',
                                    ['/planned-work-task/update', 'id' => $model->id], ['class' => 'btn btn-primary']);
                            },
                            'delete' => function ($url, PlannedWorkTask $model) {
                                return Html::a('Удалить',
                                    ['/planned-work-task/delete', 'id' => $model->id], [
                                        'data' => [
                                            'confirm' => 'Вы уверены?',
                                            'method' => 'post',
                                        ],
                                        'class' => 'btn btn-danger'
                                    ]);
                            }
                        ]
                    ],
                ],
            ]); ?>
        </div>
    </div>
</div>