controllers/InspectionController.php
<?php

namespace app\controllers;

use Yii;
use app\models\data\Inspection;
use app\models\search\InspectionSearch;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * InspectionController implements the CRUD actions for Inspection model.
 */
class InspectionController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    /**
     * Lists all Inspection models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new InspectionSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Inspection model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Inspection model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate($machine_id)
    {
        $model = new Inspection([
            'machine_id' => $machine_id
        ]);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {

            if ($model->is_problem_found) {
                return $this->redirect(['/repair-task/create', 'machine_id' => $model->machine_id]);
            }

            return $this->redirect(['update', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Inspection model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Inspection model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $model = $this->findModel($id);
        $model->delete();

        return $this->redirect(['/machine/view', 'id' => $model->machine_id]);
    }

    /**
     * Finds the Inspection model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Inspection the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Inspection::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/inspection/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\select2\Select2;
use app\models\data\Inspection;
use yii\helpers\ArrayHelper;
use app\models\data\User;
use zxbodya\yii2\galleryManager\GalleryManager;

/* @var $this yii\web\View */
/* @var $model app\models\data\Inspection */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="box box-default">
    <div class="box-body">
        <div class="inspection-form">

            <?php $form = ActiveForm::begin(); ?>

            <div class="row">
                <div class="col-md-4">
                    <?= $form->field($model, 'status')->widget(Select2::class,
                        ['data' => Inspection::getStatusList()]) ?>
                    <?= $form->field($model, 'user_id')->widget(Select2::class, [
                        'data' => ArrayHelper::map(User::getUserListByRole(User::ROLE_ENGINEER), 'id',
                            'profile.nameWithPosition'),
                        'options' => ['placeholder' => 'Выберите ответственного за осмотры'],
                    ]) ?>
                    <?= $form->field($model, 'is_problem_found')->widget(Select2::class,
                        ['data' => [0 => 'Нет', 1 => 'Да']]) ?>
                </div>
                <div class="col-md-4">
                    <?= $form->field($model, 'notes')->textarea(['rows' => 6]) ?>
                </div>
            </div>

            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <?php if ($model->isNewRecord): ?>
                            <p>Вы сможете прикрепить фотографии после сохранения.</p>
                        <?php else: ?>
                            <label>Фотографии</label>
                            <?= GalleryManager::widget([
                                'model' => $model,
                                'behaviorName' => 'galleryBehavior',
                                'apiRoute' => 'work/gallery-api'
                            ]); ?>
                        <?php endif; ?>
                    </div>
                </div>
            </div>

            <div class="form-group">
                <?= Html::submitButton('Сохранить', ['class' => 'btn btn-success']) ?>
            </div>

            <?php ActiveForm::end(); ?>

        </div>
    </div>
</div>

views/inspection/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\search\InspectionSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="inspection-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
        'options' => [
            'data-pjax' => 1
        ],
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'machine_id') ?>

    <?= $form->field($model, 'notes') ?>

    <?= $form->field($model, 'created_at') ?>

    <?= $form->field($model, 'updated_at') ?>

    <?php // echo $form->field($model, 'created_by') ?>

    <?php // echo $form->field($model, 'updated_by') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/inspection/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\data\Inspection */

$this->title = 'Провести осмотр';
$this->params['breadcrumbs'][] = ['label' => 'Оборудование', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->machine->name, 'url' => ['/machine/view', 'id' => $model->machine_id]];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="inspection-create">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/inspection/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
/* @var $this yii\web\View */
/* @var $searchModel app\models\search\InspectionSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Inspections';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="inspection-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php Pjax::begin(); ?>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Create Inspection', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            'machine_id',
            'notes',
            'created_at',
            'updated_at',
            //'created_by',
            //'updated_by',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
    <?php Pjax::end(); ?>
</div>

views/inspection/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\data\Inspection */

$this->title = $model->getName();
$this->params['breadcrumbs'][] = ['label' => 'Оборудование', 'url' => ['index']];
$this->params['breadcrumbs'][] = [
    'label' => $model->machine->name,
    'url' => ['/machine/view', 'id' => $model->machine_id]
];
$this->params['breadcrumbs'][] = [
    'label' => $model->getName(),
    'url' => ['/inspection/view', 'id' => $model->id]
];
$this->params['breadcrumbs'][] = 'Редактировать';
?>
<div class="inspection-update">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/inspection/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use app\models\data\Inspection;
use app\models\data\User;

/* @var $this yii\web\View */
/* @var $model app\models\data\Inspection */

$this->title = $model->getName();
$this->params['breadcrumbs'][] = ['label' => 'Оборудование', 'url' => ['index']];
$this->params['breadcrumbs'][] = [
    'label' => $model->machine->name,
    'url' => ['/machine/view', 'id' => $model->machine_id]
];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
$images = $model->getBehavior('galleryBehavior')->getImages();
?>
<div class="inspection-view">

    <p>
        <?php if (Yii::$app->user->can(User::ROLE_ENGINEER)): ?>
            <?= Html::a('Редактировать', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?php endif; ?>
    </p>

    <div class="box box-default">
        <div class="box-body">
            <?= DetailView::widget([
                'model' => $model,
                'attributes' => [
                    [
                        'attribute' => 'status',
                        'format' => 'raw',
                        'value' => function (Inspection $model) {
                            $labelClass = $model->status ? 'primary' : 'warning';
                            return Html::tag('span', $model->getStatusName(),
                                ['class' => 'label label-' . $labelClass]);
                        }
                    ],
                    'machine.name',
                    [
                        'attribute' => 'user_id',
                        'label' => 'Исполнитель',
                        'value' => function (Inspection $model) {
                            return $model->user->profile->name;
                        }
                    ],
                    'created_at:datetime',
                    [
                        'attribute' => 'is_problem_found',
                        'format' => 'raw',
                        'value' => function (Inspection $model) {
                            $labelClass = $model->is_problem_found ? 'danger' : 'success';
                            return Html::tag('span', Yii::$app->formatter->asBoolean($model->is_problem_found),
                                ['class' => 'label label-' . $labelClass]);
                        }
                    ],
                    'notes',
                ],
            ]) ?>
        </div>
    </div>

    <?php if (!empty($images)): ?>
        <h3>Фотографии</h3>
        <div class="box box-default">
            <div class="box-body">
                <div class="popup-gallery">
                    <?php foreach ($images as $image): ?>
                        <?= Html::a(Html::img($image->getUrl('preview'), ['width' => 100, 'height' => 100, 'style' => 'object-fit: cover;']),
                            $image->getUrl('medium'), ['title' => $image->description]) ?>
                    <?php endforeach; ?>
                </div>
            </div>
        </div>
    <?php endif; ?>
</div>